### ISSUE TITLE
deploy issue

### ISSUE THREAD

**Issue by ludi1981** [yanagishima/yanagishima#107]
I'm upgrading to version 21 since I upgrade Presto to 0.226.

When I follow the quick start, I got an error: 
git clone https://github.com/yanagishima/yanagishima.git
cd yanagishima
git checkout -b [version] refs/tags/[version]

this is mine:
[root@dev6 yanagishima]# git checkout -b 21 refs/tags/21
fatal: git checkout: updating paths is incompatible with switching branches.
Did you intend to checkout 'refs/tags/21' which can not be resolved as commit?

I tried "git checkout -b 21". It's okay. But when I typed "./gradlew distZip", I got error:
[root@dev6 yanagishima]# ./gradlew distZip

> Task :buildWeb FAILED
./deploy.sh: line 3: npm: command not found

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildWeb'.
> Process 'command './deploy.sh'' finished with non-zero exit value 127

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
1 actionable task: 1 executed

Do I miss something because I'm not formilar with gradlew? Thanks.

**Comment by ebyhr** [comment]
Does your environment have `npm`? Please install it if not exist.

**Comment by ludi1981** [comment]
> Does your environment have `npm`? Please install it if not exist.

thanks. The above problem caused by 'npm'. I installed a node.js under "/usr/local/node" to fix it.

However, now there is a permission problem. I don't understand why root can't access and create folders. The following are errors. 

[root@dev6 tmp]# git clone https://github.com/yanagishima/yanagishima.git
Initialized empty Git repository in /tmp/yanagishima/.git/
remote: Enumerating objects: 194, done.
remote: Counting objects: 100% (194/194), done.
remote: Compressing objects: 100% (153/153), done.
remote: Total 6928 (delta 72), reused 71 (delta 14), pack-reused 6734
Receiving objects: 100% (6928/6928), 44.05 MiB | 1.51 MiB/s, done.
Resolving deltas: 100% (3556/3556), done.
[root@dev6 tmp]# cd yanagishima
[root@dev6 yanagishima]# git checkout -b 21
Switched to a new branch '21'
[root@dev6 yanagishima]# ./gradlew distZip

> Task :buildWeb
Unable to save binary /tmp/yanagishima/web/node_modules/node-sass/vendor/linux-x64-64 : { Error: EACCES: permission denied, mkdir '/tmp/yanagishima/web/node_modules/node-sass/vendor'
    at Object.mkdirSync (fs.js:757:3)
    at sync (/tmp/yanagishima/web/node_modules/node-sass/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/tmp/yanagishima/web/node_modules/node-sass/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/tmp/yanagishima/web/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/tmp/yanagishima/web/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/tmp/yanagishima/web/node_modules/node-sass/vendor' }
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/node-v10.16.3-linux-x64/bin/node',
gyp verb cli   '/tmp/yanagishima/web/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.16.3 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/local/bin/python2
gyp verb check python version `/usr/local/bin/python2 -c "import sys; print "2.7.14
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.16.3
gyp verb command install [ '10.16.3' ]
gyp verb install input version string "10.16.3"
gyp verb install installing version: 10.16.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 10.16.3
gyp verb ensuring nodedir is created /root/.node-gyp/10.16.3
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.16.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/yanagishima/web/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '--node_gyp_internal_noretry', '10.16.3' ]
gyp verb install input version string "10.16.3"
gyp verb install installing version: 10.16.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 10.16.3
gyp verb ensuring nodedir is created /tmp/yanagishima/web/node_modules/node-sass/.node-gyp/10.16.3
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.16.3' ]
gyp verb remove using node-gyp dir: /tmp/yanagishima/web/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 10.16.3
gyp verb remove removing development files for version: 10.16.3
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.16.3' ]
gyp verb remove using node-gyp dir: /tmp/yanagishima/web/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 10.16.3
gyp verb remove removing development files for version: 10.16.3
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/tmp/yanagishima/web/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 2.6.32-642.el6.x86_64
gyp ERR! command "/usr/local/node-v10.16.3-linux-x64/bin/node" "/tmp/yanagishima/web/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /tmp/yanagishima/web/node_modules/node-sass
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-15T02_49_51_795Z-debug.log

> Task :buildWeb FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildWeb'.
> Process 'command './deploy.sh'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
1 actionable task: 1 executed

**Comment by ebyhr** [comment]
Could you confirm this page https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally?

**Comment by ludi1981** [comment]
> Could you confirm this page https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally?

thanks. I'm not farmily with node.js and npm. Your document is good for me. I also fixed some other problems. It seems done.

[root@dev6 yanagishima]#  ./gradlew distZip
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Task :buildWeb
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})


> Task :compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

BUILD SUCCESSFUL in 1m 43s
11 actionable tasks: 9 executed, 2 up-to-date

**Comment by CESxs** [comment]
> > Could you confirm this page https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally?
> 
> thanks. I'm not farmily with node.js and npm. Your document is good for me. I also fixed some other problems. It seems done.
> 
> [root@dev6 yanagishima]# ./gradlew distZip
> Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
> 
> > Task :buildWeb
> > npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
> > npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
> > npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> > Task :compileJava
> > Note: Some input files use unchecked or unsafe operations.
> > Note: Recompile with -Xlint:unchecked for details.
> 
> BUILD SUCCESSFUL in 1m 43s
> 11 actionable tasks: 9 executed, 2 up-to-date

how to fix it，thanks

**Comment by ludi1981** [comment]
> > > Could you confirm this page https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally?
> > 
> > 
> > thanks. I'm not farmily with node.js and npm. Your document is good for me. I also fixed some other problems. It seems done.
> > [root@dev6 yanagishima]# ./gradlew distZip
> > Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
> > > Task :buildWeb
> > > npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
> > > npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
> > > npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> > 
> > 
> > > Task :compileJava
> > > Note: Some input files use unchecked or unsafe operations.
> > > Note: Recompile with -Xlint:unchecked for details.
> > 
> > 
> > BUILD SUCCESSFUL in 1m 43s
> > 11 actionable tasks: 9 executed, 2 up-to-date
> 
> how to fix it，thanks

I followed the URL offered by ebyhr. And this section"Manually change npm’s default directory"
