### ISSUE TITLE
./gradlew distZip

### ISSUE THREAD

**Issue by myDemoMike** [yanagishima/yanagishima#165]
出现如下错误：
gyp info using node-gyp@3.7.0
gyp info using node@12.16.3 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.12\n"
gyp verb get node dir no --target version specified, falling back to host node version: 12.16.3
gyp verb command install [ '12.16.3' ]
gyp verb install input version string "12.16.3"
gyp verb install installing version: 12.16.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/12.16.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/yanagishima/web/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '--node_gyp_internal_noretry', '12.16.3' ]
gyp verb install input version string "12.16.3"
gyp verb install installing version: 12.16.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 12.16.3
gyp verb ensuring nodedir is created /usr/local/yanagishima/web/node_modules/node-sass/.node-gyp/12.16.3
gyp WARN install got an error, rolling back install
gyp verb command remove [ '12.16.3' ]
gyp verb remove using node-gyp dir: /usr/local/yanagishima/web/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 12.16.3
gyp verb remove removing development files for version: 12.16.3
gyp WARN install got an error, rolling back install
gyp verb command remove [ '12.16.3' ]
gyp verb remove using node-gyp dir: /usr/local/yanagishima/web/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 12.16.3
gyp verb remove removing development files for version: 12.16.3
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/yanagishima/web/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 4.4.0-116-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/yanagishima/web/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/local/yanagishima/web/node_modules/node-sass
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN bootstrap@4.1.3 requires a peer of popper.js@^1.14.3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.9.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-22T10_33_33_049Z-debug.log

**Comment by thirdparty-core** [comment]
解决了吗，我也是这个问题，如果解决了，告知一下，3q

**Comment by thirdparty-core** [comment]
关键错误信息：
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/yanagishima/web/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 4.4.0-116-generic

解决方案：
cd web
sudo npm install --unsafe-perm
安装完成后cd .. 出去
继续 ./gradlew distZip
✅

**Comment by ebyhr** [comment]
Going to close this issue because you already resolved. Could you please post in English from next time? Thanks.
