### ISSUE TITLE
All Query List, History, Bookmark empty

### ISSUE THREAD

**Issue by elvizlai** [yanagishima/yanagishima#179]
**Describe the feature**:

**yanagishima version**:
22 (also tried master version)

**presto version**:
341

**conf/yanagishima.properties**:

**JVM version** (`java -version`):

**Server OS version** (`uname -a` if on a Unix-like system):

**Client OS version**

**Browser**:
Mac OSX Chrome 85

**Description of the problem including expected versus actual behavior**:

All `Query List, History, Bookmark` empty

`Bookmark` only works for storage `Browser`

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) query execution, bookmark, settings, hisotry etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

there is http response `{"error":"Basic authentication or X-Presto-User must be sent","code":401}`	

**Provide screenshots (if relevant)**:

**Comment by ebyhr** [comment]
@elvizlai Please try the latest upstream again that has relevant commit (merged on Nov 25) https://github.com/yanagishima/yanagishima/commit/7d78f7059dc73a3c95c8ad66474919ae0f4a2563
