### ISSUE TITLE
Visit home page and get js error 

### ISSUE THREAD

**Issue by simple365** [yanagishima/yanagishima#22]
**yanagishima version**: 6.0

**presto version**:0.170

**conf/yanagishima.properties**:
```
jetty.port=8280
presto.query.max-run-time-seconds=1800
presto.max-result-file-byte-size=1073741824
presto.datasources=ha-presto
presto.coordinator.server.ha-presto=http://localhost:8889
presto.redirect.server.ha-presto=http://localhost:8889
catalog.ha-presto=hive
schema.ha-presto=default
select.limit=500
audit.http.header.name=some.auth.header
to.values.query.limit=500
check.datasource=false
```

**JVM version** (`java -version`): openjdk version "1.8.0_141"

**Server OS version** :Linux  4.4.35-33.55.amzn1.x86_64

**Client OS version**:windows 7

**Browser**: chrome

1. open the home page http://127.0.0.1:8280
2. get js error code and the `function, table completion(ESC)` does not work
![1](https://user-images.githubusercontent.com/2282908/29349207-10131080-828b-11e7-911e-adc9de247c23.png)

**Comment by wyukawa** [comment]
Sorry, now Ctrl+Space is the key of Auto-complate Table/Function
