### ISSUE TITLE
Support multiple statements in a singe query for HIVE

### ISSUE THREAD

**Issue by hamlet-lee** [yanagishima/yanagishima#24]
Currently yanagishima do not support multiple statements in a single query, for example:

```
create temporary table tmp1 as select .... ;
create temporary table tmp2 as select .... ;
select count(*) from tmp1 join tmp2 on (...) where ... ;
```

Highly recommend to support multiple statements in a single query.

I propose the result of multiple statements query simply like below:

```
table 1: no result set

table 2: no result set

table 3: a table shows result set
```

**Comment by wyukawa** [comment]
Sorry about the delay.
But currently there is no plan to support multiple statements due to no needs in my environment.

**Comment by ebyhr** [comment]
Let's edit the issue title to `feature request: Support multiple statements` or something better because other people may misunderstand this is Hive specific issue. Then we can close #49.
