### ISSUE TITLE
Sugar.js : date is not valid

### ISSUE THREAD

**Issue by parisni** [yanagishima/yanagishima#25]
**yanagishima version**: 10

**presto version**: 0.187

**JVM version** (`java -version`): openjdk version "1.8.0_151"

**Browser**: chome

Hi

I am querying a presto coordinator. I am able to scroll over tables and schemas in the treeview. The queries I am running are succeeding (from presto admin serveur) and I am able to read the tsv in the result filesystem.
However, the webclient does not show the results (in firefox or chrome), and I get that error in the console of chrome:

```
vue.min.js:6 TypeError: Date is not valid
    at Nc (sugar.min.js:31)
    at Wc (sugar.min.js:37)
    at format (sugar.min.js:97)
    at Date.<anonymous> (sugar.min.js:13)
    at extractDate (index.js:2659)
    at pt.eval (eval at yi (vue.min.js:7), <anonymous>:2:19170)
    at pt.e._render (vue.min.js:7)
    at pt.r (vue.min.js:6)
    at So.get (vue.min.js:7)
    at So.run (vue.min.js:7)
C @ vue.min.js:6
```

Apparently a problem with sugar.js ?

Thanks

**Comment by parisni** [comment]
I finally edited the html source  code of index.html as a workaround.

```html
<!-- <span class="mr-2" v-if="response.result.finishedTime">
                                                                                <i class="fa fa-calendar" title="Finished time" data-toggle="tooltip" data-animation="false" data-placement="left"></i>
                              {{response.result.finishedTime | extractDate}}
                                         </span>
-->
```

**Comment by fjaros** [comment]
Fixed by https://github.com/yanagishima/yanagishima/pull/26
