### ISSUE TITLE
presto csv export encoding

### ISSUE THREAD

**Issue by parisni** [yanagishima/yanagishima#27]
Hi

When exporting textual content through tsv way, the encoding is fine (utf-8)
However, when exporting a csv, the encoding is broken. Looks like the csv transformation step does not handle utf8 well

Thanks

**Comment by wyukawa** [comment]
yanagishima exports a csv file in Shift_JIS encoding because Japanese character is not garbled in Excel.

**Comment by parisni** [comment]
OK.

Any way to get them compressed ? (zip, gzip)

**Comment by wyukawa** [comment]
ah, currently, there is no way to get them compressed.
I will consider compression and CSV for UTF-8.
Thanks.

**Comment by wyukawa** [comment]
Yanagishima 11.0 supports UTF-8 encoding for CSV but currently there is no plan to implement compression due to no needs in my environment.

**Comment by ebyhr** [comment]
Let's create a new issue for compression if needed.
