### ISSUE TITLE
WEB UI HTTP ERROR: 404

### ISSUE THREAD

**Issue by imperio-wxm** [yanagishima/yanagishima#28]
**Describe the feature**:

When I start server, web ui like this but no error logs:

```java
HTTP ERROR: 404
Problem accessing /. Reason:

Not Found
Powered by Jetty:// 9.3.13.M0
```

**yanagishima version**:

3.0

**presto version**:

0.149

**conf/yanagishima.properties**:

````java
jetty.port=8081
presto.query.max-run-time-seconds=1800
presto.max-result-file-byte-size=1073741824
presto.datasources=presto1
presto.coordinator.server.presto1=http://:8080
presto.redirect.server.presto1=http://:8080
catalog.presto1=xxxx
schema.presto1=xxxx
select.limit=500
audit.http.header.name=http
````

**JVM version** (`java -version`):

java version "1.8.0_60"

**Server OS version** (`uname -a` if on a Unix-like system):

Linux xxxx-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by wyukawa** [comment]
please use yanagishima 11.0 because 3.0 is too old.
