### ISSUE TITLE
Security with user / password - access to other query results

### ISSUE THREAD

**Issue by parisni** [yanagishima/yanagishima#29]
I am using yanagishima 10 / presto 195.

I have setup the ssl connection with user and password. Then the user need to login, and this works great.

The concern is about the  `query list` panel: all users are able to read any result from other users, and worst, get their results.

Then the question is, have you in mind an update that would secure the access to other users queries at the backend level ?

Thanks

**Comment by wyukawa** [comment]
Thank you for reporting and I understand what you mean.
For example, if query list panel disappears(of course, it's configurable in server side setting), does it meet your request?

Of course, any ideas are welcome.

Thanks

**Comment by parisni** [comment]
Sure, I could only keep the query panel. However, the history panel is useful. 

I would say a robust design would be the backend verify the identity of the requester before any request.
Then when userA ask for previous queries, then backend reads the userA/ folder.

In case of no ssl security, then there is only the default user folder, and all are sharing it

**Comment by daikon12** [comment]
> For example, if query list panel disappears(of course, it's configurable in server side setting), does it meet your request?


hi wyukawa:
If I want query list panel disappears but keep the history panel,how should I configure in the server side setting , Do I need to modify the source code , and rebuild?

Thanks

**Comment by parisni** [comment]
@daikon12  yes, I d'say you have no built-in solution

**Comment by daikon12** [comment]
> @daikon12 yes, I d'say you have no built-in solution
@parisni  you are right,Thank you for your quick reply .

 In order to  make the query list panel disappears ,how do you configure in the server side setting

Thanks

**Comment by wyukawa** [comment]
Unfortunately, there is no such kind of configuration now

**Comment by achunero** [comment]
@parisni can you pleas share on how you setup the username/password for the UI

I've been trying to set this up but running into errors like "Authentication using username/password requires HTTPS to be enabled"

I'm trying to setup nginx infront of this, so i can authenticate ppl using nginx. I'm not sure how i can tie the username/password for the UI to nginx that is running on top. Can you please let me how you setup ?

**Comment by parisni** [comment]
@achunero as far as I remember (i do not use presto anymore), I had implemented basic auth in presto as a plugin. Then I was able to bridge yanagishima and presto .

in your case, nginx should transmit the auth to yanagishima in order it transmit to presto. hope this helps

**Comment by ebyhr** [comment]
@achunero Does your Presto coordinator hostname in property starts with `https`?

**Comment by achunero** [comment]
No I does not. We are using nginx on top of presto currently to
authenticate we were thinking of replacing that with yanagishima + nginx
for authentication. Does that make sense?

**Comment by ebyhr** [comment]
While your approach looks good, I confirmed there's a bug in QueryServlet.java. Let me fix it first.

**Comment by ebyhr** [comment]
Let me ask one more question before answering it. Did you set `auth.<datasource>` in yanagishima.properties?

**Comment by achunero** [comment]
No I did not set auth.datasource. all I did was auth.presto to true,
user.required to true

Im still playing with the tool to figure what works

**Comment by ebyhr** [comment]
My comment `auth.<datasource>` means `auth.presto` in your case. It will not work until you disabling the flag with the non-https Presto.

**Comment by datta90** [comment]
was anyone able to connect https enabled presto
