### ISSUE TITLE
buildWeb Failed 

### ISSUE THREAD

**Issue by mtejagithub** [yanagishima/yanagishima#291]
Hi , 
I go this issue while installing , 

Command :  gradlew distZip

Starting a Gradle Daemon (subsequent builds will be faster)
> Task :buildWeb FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildWeb'.
> A problem occurred starting process 'command './deploy.sh''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 56s
1 actionable task: 1 executed

**Comment by mtejagithub** [comment]
Hi, Thanks for responding. Upadated node-sass to 4.14.1 . still getting the issue . 

Does this work  in windows ?

> Task :buildWeb FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildWeb'.
> A problem occurred starting process 'command './deploy.sh''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed

**Comment by ebyhr** [comment]
@mtejagithub As far as I tested on GitHub Actions https://github.com/yanagishima/yanagishima/pull/292, we could build on Windows. Could you run the below commands in web directory and share the error message?
```bash
npm install
npm run build
```

**Comment by mtejagithub** [comment]
Hi ,  i have run the commands  in web , This was the output . 

C:\Users\user\Desktop\ProjectNewCastle\Yanagishima\yanagishima\web>npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> node-sass@4.14.1 install C:\Users\user\Desktop\ProjectNewCastle\Yanagishima\yanagishima\web\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/win32-x64-83_binding.node
Download complete .] - :
Binary saved to C:\Users\user\Desktop\ProjectNewCastle\Yanagishima\yanagishima\web\node_modules\node-sass\vendor\win32-x64-83\binding.node
Caching binary to C:\Users\user\AppData\Roaming\npm-cache\node-sass\4.14.1\win32-x64-83_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall C:\Users\user\Desktop\ProjectNewCastle\Yanagishima\yanagishima\web\node_modules\webpack\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.14.1 postinstall C:\Users\user\Desktop\ProjectNewCastle\Yanagishima\yanagishima\web\node_modules\node-sass
> node scripts/build.js

Binary found at C:\Users\user\Desktop\ProjectNewCastle\Yanagishima\yanagishima\web\node_modules\node-sass\vendor\win32-x64-83\binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1368 packages from 1012 contributors and audited 1440 packages in 232.44s

2 packages are looking for funding
  run `npm fund` for details

found 870 vulnerabilities (522 low, 18 moderate, 330 high)
  run `npm audit fix` to fix them, or `npm audit` for details

- building for production...(node:11252) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)ishima\yanagishima\web
(node:11252) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:11252) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
Hash: 80a9cb445c92a7513613
Version: webpack 3.12.0
Time: 111793ms
                                                  Asset       Size  Chunks                    Chunk Names
                  static/js/viz.cae2938e20bbbff93010.js    1.95 MB       0  [emitted]  [big]  viz
            static/js/diff-view.c9a312bd63ab7cb95dcb.js     847 kB       1  [emitted]  [big]  diff-view
               static/js/vendor.c645c69e2b54a9e18e2f.js    1.19 MB       2  [emitted]  [big]  vendor
                  static/js/app.c0c59b1a7114fc95268a.js     219 kB       3  [emitted]         app
             static/js/manifest.bd3691bb4299ce40b3f8.js    1.51 kB       4  [emitted]         manifest
    static/css/app.f78c5a0380a6d789a0afeb84106f2eb1.css     175 kB       3  [emitted]         app
static/css/app.f78c5a0380a6d789a0afeb84106f2eb1.css.map     342 kB          [emitted]
              static/js/viz.cae2938e20bbbff93010.js.map    5.08 MB       0  [emitted]         viz
        static/js/diff-view.c9a312bd63ab7cb95dcb.js.map    1.73 MB       1  [emitted]         diff-view
           static/js/vendor.c645c69e2b54a9e18e2f.js.map    4.48 MB       2  [emitted]         vendor
              static/js/app.c0c59b1a7114fc95268a.js.map     686 kB       3  [emitted]         app
         static/js/manifest.bd3691bb4299ce40b3f8.js.map    7.87 kB       4  [emitted]         manifest
                                             index.html  771 bytes          [emitted]
                                     static/favicon.ico    15.1 kB          [emitted]

  Build complete.

  Tip: built files are meant to be served over an HTTP server.
  Opening index.html over file:// won't work.


C:\Users\user\Desktop\ProjectNewCastle\Yanagishima\yanagishima\web>

**Comment by ebyhr** [comment]
The message looks only `npm install`. Please run `npm run build` next.

**Comment by mtejagithub** [comment]
Hi , i have used  npm run build ,  
C:\Users\user\Desktop\ProjectNewCastle\Yanagishima\yanagishima\web>npm run build next

> yanagishima@22.0.0 build C:\Users\user\Desktop\ProjectNewCastle\Yanagishima\yanagishima\web
> node build/build.js "next"

- building for production...(node:9708) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9708) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:9708) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
Hash: b1c2fc121fd0aa181940
Version: webpack 3.12.0
Time: 96333ms
                                                  Asset       Size  Chunks                    Chunk Names
                  static/js/viz.cae2938e20bbbff93010.js    1.95 MB       0  [emitted]  [big]  viz
            static/js/diff-view.c9a312bd63ab7cb95dcb.js     847 kB       1  [emitted]  [big]  diff-view
               static/js/vendor.c645c69e2b54a9e18e2f.js    1.19 MB       2  [emitted]  [big]  vendor
                  static/js/app.c0c59b1a7114fc95268a.js     219 kB       3  [emitted]         app
             static/js/manifest.bd3691bb4299ce40b3f8.js    1.51 kB       4  [emitted]         manifest
    static/css/app.f78c5a0380a6d789a0afeb84106f2eb1.css     175 kB       3  [emitted]         app
static/css/app.f78c5a0380a6d789a0afeb84106f2eb1.css.map     342 kB          [emitted]
              static/js/viz.cae2938e20bbbff93010.js.map    5.08 MB       0  [emitted]         viz
        static/js/diff-view.c9a312bd63ab7cb95dcb.js.map    1.73 MB       1  [emitted]         diff-view
           static/js/vendor.c645c69e2b54a9e18e2f.js.map    4.48 MB       2  [emitted]         vendor
              static/js/app.c0c59b1a7114fc95268a.js.map     686 kB       3  [emitted]         app
         static/js/manifest.bd3691bb4299ce40b3f8.js.map    7.87 kB       4  [emitted]         manifest
                                             index.html  771 bytes          [emitted]
                                     static/favicon.ico    15.1 kB          [emitted]

  Build complete.

  Tip: built files are meant to be served over an HTTP server.
  Opening index.html over file:// won't work.

**Comment by ebyhr** [comment]
Thanks, `next` should be omitted, but realized npm is no problem. I guess `web/deploy.sh` is the problem now. I'm sorry, but could you try modifying the shell script and build.gradle so that you can build on Windows?

**Comment by ebyhr** [comment]
This issue should be fixed in docker support. Let me close.
