### ISSUE TITLE
results directory filling up with space

### ISSUE THREAD

**Issue by jgtree420** [yanagishima/yanagishima#31]
Our server is filling up with result files.
I think the following features would be awesome.
1. Could you add a configuration to change the location of the stored results?  Currently results are stored under <yanagishima_home>/result
2. Could you add a configuration to remove older result files. For example results older than X days.

Thanks!

**Comment by wyukawa** [comment]
Sorry for replying so late.
I may consider this features but currently, I have no resource to implement...
