### ISSUE TITLE
how support spark sql

### ISSUE THREAD

**Issue by Maplejw** [yanagishima/yanagishima#314]
**Describe the feature**:Engine use spark, but it always uses hive by mapreduce.

**yanagishima version**:20.0

**conf/yanagishima.properties**:
```
# yanagishima web port
jetty.port=8080
spark.web.url.your-spark=http://10.0.3.163:18080
spark.jdbc.url.your-spark=jdbc:hive2://10.0.3.163:2181,10.0.3.164:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2_zk
resource.manager.url.your-spark=http://10.0.3.163:8088
sql.query.engines=spark
spark.datasources=your-spark
hive.query.max-run-time-seconds.your-spark=3600
```

**JVM version** (`java -version`): jdk8

It seems spark not takes effect.

**Comment by ebyhr** [comment]
> it always uses hive by mapreduce

How did you check it?

**Comment by Maplejw** [comment]
> > it always uses hive by mapreduce
> 
> How did you check it?

By check yarn UI. 
![image](https://user-images.githubusercontent.com/24646597/116529812-e6fee480-a90f-11eb-83a0-384d85559e8b.png)

**Comment by ebyhr** [comment]
I roughly guess you are connecting to Hiveserver2, not Spark Thrift server.

**Comment by ddww** [comment]
I would like to ask, what value is filled in for "spark.web.url.your-spark" and what does it mean
