### ISSUE TITLE
Remove support for Elasticsearch

### ISSUE THREAD

**Issue by ebyhr** [yanagishima/yanagishima#321]
Let's remove unused feature if no one leave negative opinion in June.

**Comment by JerryLen** [comment]
I think it's a useful feature. Maybe we can keep it.

**Comment by ebyhr** [comment]
@JerryLen Are you using the feature in production?

**Comment by JerryLen** [comment]
Ready for production,  it's a simple alternative to trino.
If not necessary, i think we can keep it temporarily.   ^_^

**Comment by ebyhr** [comment]
If it's not yet used, I strongly recommend using other tool.

**Comment by JerryLen** [comment]
Alright, thanks for your suggestion.
