### ISSUE TITLE
the index.html includes http URL couldnt show in internal network

### ISSUE THREAD

**Issue by ludi1981** [yanagishima/yanagishima#33]
**Describe the feature**:

**yanagishima version**:12.0

**presto version**:0.202

**conf/yanagishima.properties**:
jetty.port=38080
presto.query.max-run-time-seconds=1800
presto.max-result-file-byte-size=1073741824
presto.datasources=dev
auth.your-presto=false
presto.coordinator.server.dev=http://node101:28080
presto.redirect.server.dev=http://node101:28080
catalog.dev=hive
schema.dev=default
select.limit=500
audit.http.header.name=some.auth.header
use.audit.http.header.name=false
to.values.query.limit=500
check.datasource=false
hive.jdbc.url.your-hive=jdbc:hive2://node101:10000/default;auth=noSasl
hive.jdbc.user.your-hive=root
hive.jdbc.password.your-hive=root
hive.query.max-run-time-seconds=3600
hive.query.max-run-time-seconds.your-hive=3600
resource.manager.url.your-hive=http://node101:8088
sql.query.engines=presto
hive.datasources=your-hive
hive.disallowed.keywords.your-hive=insert,drop
hive.max-result-file-byte-size=1073741824
hive.setup.query.path.your-hive=/opt/app/hive/conf/
cors.enabled=false

**JVM version** (`java -version`):1.8.0_151

**Server OS version** (`uname -a` if on a Unix-like system): CentOS 7.2

**Client OS version**CENTOS 7.2

**Browser**:Google Chrome v63

**Description of the problem including expected versus actual behavior**: I'm not sure if this is a bug or feature. So, I post as a bug first. In my environment, the presto was deploy in internal network. The server counldn't access Internet. When I visit the  yanagishima service by browser, it shows blank page. The reason is the browser can't get the ccs or js files. For example, the URL in the "link href=" line. Is it possbile include these js/css files in next releases? Such as, ace.js, bootstrap.min.js, and etc.

**Steps to reproduce**: put the service in internal network

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) query execution, bookmark, settings, hisotry etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:NA
	
**Provide screenshots (if relevant)**:NA

**Comment by wyukawa** [comment]
Sorry for replying so late.
I've wanted to include js/css files someday but I haven't been able to yet.

**Comment by enoughwell** [comment]
> Sorry for replying so late.
> I've wanted to include js/css files someday but I haven't been able to yet.

Is this problem solved now?
