### ISSUE TITLE
Error NoSuchMethodError while trying to use hive

### ISSUE THREAD

**Issue by parisni** [yanagishima/yanagishima#34]
Hi

I get that error while starting the tool:
I have it in both V10 and V12 and both HIVE 1.2.1 and HIVE 2.1.0

Any help appreciated !

regards,

> 
>  ERROR [HiveServlet] [Yanagishima] com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()Lcom/google/common/util/concurrent/ListeningExecutorService;
> java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()Lcom/google/common/util/concurrent/ListeningExecutorService;
> 	at org.apache.curator.framework.listen.ListenerContainer.addListener(ListenerContainer.java:40)
> 	at org.apache.curator.framework.imps.CuratorFrameworkImpl.start(CuratorFrameworkImpl.java:246)
> 	at org.apache.hive.jdbc.ZooKeeperHiveClientHelper.configureConnParams(ZooKeeperHiveClientHelper.java:62)
> 	at org.apache.hive.jdbc.Utils.configureConnParams(Utils.java:509)
> 	at org.apache.hive.jdbc.Utils.parseURL(Utils.java:429)
> 	at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:134)
> 	at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:105)
> 	at java.sql.DriverManager.getConnection(DriverManager.java:664)
> 	at java.sql.DriverManager.getConnection(DriverManager.java:247)

**Comment by wyukawa** [comment]
Sorry for replying so late.
But it's a weird situation.
Maybe, deploy or packaging miss?
Anyway, please follow the issue template.
