### ISSUE TITLE
Add retry logic in hive jdbc level

### ISSUE THREAD

**Issue by wyukawa** [yanagishima/yanagishima#345]
**Expected Behavior**

Add retry logic in hive jdbc level like `;retries=3`
https://github.com/apache/hive/blob/820662a703e347badf79c0a286c8b22c57f244ca/jdbc/src/java/org/apache/hive/jdbc/Utils.java#L89

**Current Behavior**

no retry

**Context**

Sometimes hiveserver2 is unstable, it would be great if we add retry logic

**Comment by ebyhr** [comment]
This is just a configuration, not Java code.
