### ISSUE TITLE
Hive views are not supported

### ISSUE THREAD

**Issue by imperio-wxm** [yanagishima/yanagishima#35]
**Describe the feature**:

![image](https://user-images.githubusercontent.com/8111349/42628576-1ccda71e-8603-11e8-895d-ba65792921a0.png)

yanagishima can not select hive view.

**yanagishima version**:

version: 11.0

**presto version**:

vesion: 0.205

**conf/yanagishima.properties**:
```java
jetty.port=8889
presto.datasources=prod_offline
presto.coordinator.server.prod_offline=http://xxxx:8888
catalog.prod_offline=hive
schema.prod_offline=dw
sql.query.engines=presto
```
**JVM version** (`java -version`):

java version "1.8.0_60"

**Comment by wyukawa** [comment]
Presto doesn't support hive view.
Please use engine=hive in yanagishima.
