### ISSUE TITLE
Not able to run gradle build for yanagishima 22

### ISSUE THREAD

**Issue by datta90** [yanagishima/yanagishima#353]
**Yanagishima version**:22

**Presto version**:350

**conf/application.yml**:

**JVM version** (`java -version`):openjdk11.10

**Server OS version** (`uname -a` if on a Unix-like system): ubuntu 20.04

**Client OS version**:ubuntu 20.04

**Browser**:firefox

**Description of the problem including expected versus actual behavior**:
not able to build yanagishima zip file
using gradle version 5.2

**Steps to reproduce**: gradle distZip

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) query execution, bookmark, settings, hisotry etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

[Fatal Error] gradle-errorprone-plugin-1.1.1.pom:2:10: Already seen doctype.
> Configure project :

 

FAILURE: Build failed with an exception.

 

* What went wrong:
A problem occurred configuring root project 'yanagishima'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve net.ltgt.gradle:gradle-errorprone-plugin:1.1.1.
     Required by:
         project :
      > Could not resolve net.ltgt.gradle:gradle-errorprone-plugin:1.1.1.
         > Could not parse POM https://plugins.gradle.org/m2/net/ltgt/gradle/gradle-errorprone-plugin/1.1.1/gradle-errorprone-plugin-1.1.1.pom
            > Already seen doctype.

 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

 

* Get more help at https://help.gradle.org

 

BUILD FAILED in 6s
	
**Provide screenshots (if relevant)**:

**Comment by ebyhr** [comment]
Are you using internal mirror maven server?

**Comment by datta90** [comment]
no its over the internet . only i am accessing the internet via proxy . i searched a bit and found gradle's proxy config . so its now working 
thanks
