### ISSUE TITLE
query about array

### ISSUE THREAD

**Issue by lionkingk** [yanagishima/yanagishima#37]
**Describe the feature**:

**yanagishima version**:14.0

**presto version**:0.206

**conf/yanagishima.properties**:

jetty.port=8982
presto.query.max-run-time-seconds=1800
presto.max-result-file-byte-size=1073741824
presto.datasources=yixin-presto
auth.yixin-presto=false
presto.coordinator.server.yixin-presto=http://10.134.0.46:8980
presto.redirect.server.yixin-presto=http://10.134.0.46:8980
catalog.yixin-presto=hive
schema.yixin-presto=kg
select.limit=5000
audit.http.header.name=some.auth.header
use.audit.http.header.name=false
to.values.query.limit=500
check.datasource=false
hive.jdbc.url.yixin-hive=jdbc:hive2://c1-hd-nn1:2181,c1-hd-nn2:2181,c1-hd-nn3:2181/;auth=noSasl
hive.jdbc.user.yixin-hive=yisou
hive.jdbc.password.yixin-hive=9Kraq+h1Q
hive.query.max-run-time-seconds=3600
hive.query.max-run-time-seconds.your-hive=3600
resource.manager.url.yixin-hive=thrift://c1-hd-dn31.bdp.idc:9088
sql.query.engines=presto
hive.datasources=yixin-hive
hive.disallowed.keywords.yixin-hive=insert,drop
hive.max-result-file-byte-size=1073741824
hive.setup.query.path.yixin-hive=/usr/local/yanagishima/conf/hive_setup_query_your-hive
cors.enabled=false

**JVM version** (`java -version`):1.8.0_181

**Server OS version** (`uname -a` if on a Unix-like system):
Linux c2-hd-dn31 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Client OS version**：
Darwin lionkingkdeMacBook-Pro.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64

**Browser**:Chrome

**Description of the problem including expected versus actual behavior**:
when I create a table like this:
CREATE TABLE temp (
   a array(row(name varchar, mobile varchar))
)
and I 'select * from temp' then it will preparing all the time
**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) query execution, bookmark, settings, hisotry etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:
	
**Provide screenshots (if relevant)**:

**Comment by wyukawa** [comment]
Thank you for reporting.
I check log and then think this is presto issue https://github.com/prestodb/presto/issues/11216

**Comment by wyukawa** [comment]
Aside from presto issue, I improved error handling.

fix infinite loop bug in https://github.com/yanagishima/yanagishima/commit/95e009cd5601a4ba2f7b8fe5ed891e45db48c798
