### ISSUE TITLE
Error when modify  presto.max-result-file-byte-size

### ISSUE THREAD

**Issue by daikon12** [yanagishima/yanagishima#38]
Demand：
The result size of my query is more than 1GB。

Operation：
yanagishima version:12.0
presto version:0.211
I modified a property value  in conf/yanagishima.properties:
-----------------------------------------------------
presto.max-result-file-byte-size=10737418240
-----------------------------------------------------
the default  property value  is 1073741824

Result：
The status of my query is failed
Error: java.NumberFormatException: For input string：“10737418240”

How should I do?  Is the property value cannot modified?

**Comment by wyukawa** [comment]
Unfortunately, Int.MaxValue(2147483647) is the maximum in the current implementation.
Please use a smaller value.

**Comment by daikon12** [comment]
hi wyukawa ,
Thank you for your rapid  reply , You really did me a big favor .  I works .
Thank you very much again.

**Comment by dollyshukla** [comment]
Hi wyukawa, 
As in oracle tools we can download files of higher size, it takes rime to so so. Can we have this feature in Yanagishima where we can download records in some millions or more?
Or is it there , may be I am not aware of.
Need your help in getting UI tool on presto , to download large files.

**Comment by wwwwwwchun** [comment]
i set value presto.max-result-file-byte-size=10737418240,if i need to change this values?

**Comment by ebyhr** [comment]
@wwwwwwchun Yes, you need to change the value.

**Comment by wwwwwwchun** [comment]
thanks,when i change this value,the server is running

**Comment by ebyhr** [comment]
Thanks for your confirmation. Could you please close the issue https://github.com/yanagishima/yanagishima/issues/85 ?
