### ISSUE TITLE
the table info do not display comment info of the table filed,but display wrong value of Partition Key values.

### ISSUE THREAD

**Issue by piaolingzxh** [yanagishima/yanagishima#41]
**Describe the feature**:

**yanagishima version**:14.0

**presto version**:0.107

**conf/yanagishima.properties**:

**JVM version** (`java -version`):1.8.0_101

**Server OS version** (`uname -a` if on a Unix-like system):
2.6.32-642.el6.x86_64 #1 SMP Tue May 10 17:27:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Client OS version**

**Browser**:chrome 68.0.3440.106

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) query execution, bookmark, settings, hisotry etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.select one 'mysql' data type catalog in "treeview" pannel. 
 2.select one "schema" and "table" ,
 3.then wen can get  all the fields of the selected presto table  from  the "column"  html table. 
the "column" result have 4 headers.(Column,Type,Extra,Comment).
BUG:  the html table  header and value do not match after third html column,(ref snapshot)
note: we can get the ajax result "data.headers" from chrome ,and find the headers have five info.["Column", "Type", "Null", "Partition Key", "Comment"].
and also we get the data.result have comment info,but display nothing.

**Provide logs (if relevant)**:
	
**Provide screenshots (if relevant)**:
 
![yanagishima](https://user-images.githubusercontent.com/3400849/48174874-a62c4300-e344-11e8-9699-46bfc502d919.png)

**Comment by wyukawa** [comment]
It's weird.
I'm not sure why ["Column", "Type", "Null", "Partition Key", "Comment"] returns.
["Column", "Type", "Partition Key", "Comment"] is correct.
But presto 0.107 is too old, please try 0.213.
Thanks

**Comment by ebyhr** [comment]
Going to close this issue since the version is too old. Please reopen if the issue still happens on newer version (Presto > 300).
