### ISSUE TITLE
WEB UI HTTP ERROR: 404

### ISSUE THREAD

**Issue by wmfxly** [yanagishima/yanagishima#44]
*WEB UI HTTP ERROR: 404**:

**yanagishima 16.0**:

**presto version presto-server-0.214**:

**conf/yanagishima.properties**:

jetty.port=8088
presto.query.max-run-time-seconds=1800
presto.max-result-file-byte-size=1073741824
presto.datasources=presto1
auth.your-presto=false

presto.coordinator.server.presto1=http://localhost:8081
presto.redirect.server.presto1=http://localhost:8081
catalog.presto1=mongodb
schema.presto1=test
select.limit=500
to.values.query.limit=500
check.datasource=false
sql.query.engines=presto
cors.enabled=false

**JVM version** (`java -version`):
[root@localhost target]# java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

**Server OS version** (`uname -a` if on a Unix-like system):

[root@localhost target]# uname -a
Linux xxxxxxx.xxx 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Browser**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
start yanagishima but i see 404 not found

**Comment by wmfxly** [comment]
I solved this problem, I think it is the package script or the startup script should find this correct web path. But can't find the correct web directory.

**Comment by sukidasakura** [comment]
> I solved this problem, I think it is the package script or the startup script should find this correct web path. But can't find the correct web directory.

Can I ask how to solve this problem? I met this problem too.

**Comment by dkim010** [comment]
> > I solved this problem, I think it is the package script or the startup script should find this correct web path. But can't find the correct web directory.
> 
> Can I ask how to solve this problem? I met this problem too.

I solved by executing `yanagishima-start.sh` in yanagishima application home directory.
The directory includes `bin/`, `conf/`, `lib`, and so on.
I guess that yanagishima is referring to current path.

**Comment by ducking-repo** [comment]
> 我解决了这个问题，我认为应该是程序包脚本或启动脚本找到此正确的Web路径。但是找不到正确的Web目录。

There is no Web directory in my compiled home directory. Why?
