### ISSUE TITLE
WEB UI Publish button is invalid

### ISSUE THREAD

**Issue by devilcony** [yanagishima/yanagishima#46]
**yanagishima version**:17.0

**presto version**:0.213

**JVM version** (`java -version`):1.8.0_111

**Server OS version** (`uname -a` if on a Unix-like system):
2.6.32-431.29.2.el6.x86_64 #1 SMP Tue Sep 9 21:36:05 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Client OS version**:win10

**Browser**:chrome 67.0.3396.62

**Description of the problem including expected versus actual behavior**:
the publish button is invalid in my browser

**Steps to reproduce**:

 1.run a query
 2.click the Publish button 
 3.nothing happened

**Provide logs (if relevant)**:
debug and find this exception:
	TypeError: Cannot read property 'writeText' of undefined at http://10.250.100.49:8888/static/js/app.84b92e77a1367ea5c61c.js:1:72953

code: web\src\components\tabs\TabResult.vue: line 396
```javascript
    if (ua.indexOf('chrome') !== -1) {
      navigator.clipboard.writeText(`${location.protocol}//${location.host}${path}`)
    }
```
navigator.clipboard reutnrs undefined
i tried to fix the code like this,just for suggestion:
```javascript
    if (ua.indexOf('chrome') !== -1 && navigator.clipboard) {
      navigator.clipboard.writeText(`${location.protocol}//${location.host}${path}`)
    }
```

iv find some info here ,hope it will be helpful :
https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined

**Comment by wyukawa** [comment]
Thank you for reporting.
Do you deploy your yanagishima in HTTP?
If so, I recommend using HTTPS.

**Comment by wyukawa** [comment]
And also I can't reproduce in my chrome(ver 71)

**Comment by ebyhr** [comment]
I could reproduce it with 71.0.3578.98 on macOS 10.13.6. 
In my case, http://localhost:8080... and http://127.0.0.1:8080... works, but http://yanagishima:8080... doesn't. The hostname `yanagishima` points to 127.0.0.1 in /etc/hosts.

**Comment by wyukawa** [comment]
Ah, I see. I was able to reproduce.
I will fix.
Thanks!
