### ISSUE TITLE
Bad query gets stuck in Preparing loop

### ISSUE THREAD

**Issue by Bcpoole** [yanagishima/yanagishima#48]
**yanagishima version**: 17.0

**presto version**: 0.215

**conf/yanagishima.properties**:
jetty.port=8088
presto.query.max-run-time-seconds=14400
presto.max-result-file-byte-size=1073741824
presto.datasources=reporting
presto.coordinator.server.reporting=http://...:8080
presto.redirect.server.reporting=http:/...:8080
catalog.reporting=hive
schema.reporting=default
select.limit=500
audit.http.header.name=some.auth.header
to.values.query.limit=500
check.datasource=false
sql.query.engines=presto

**JVM version** (`java -version`): java version "1.7.0_45"

**Server OS version** (`uname -a` if on a Unix-like system):
Linux 2.6.32-220.el6.x86_64 #1 SMP Tue Dec 6 19:48:22 GMT 2011 x86_64 x86_64 x86_64 GNU/Linux

**Client OS version**
Darwin MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64

**Browser**: Chrome, Vivaldi, Safari

**Description of the problem including expected versus actual behavior**: When running a bad query, the **Result** tab gets stuck with the header Loading and a Preparing loader. This also blocks the input box and Run + Explain buttons. Was this introduced when switching frontend to Vue.js (we recently upgraded from a version prior to Vue.js use)?

**Steps to reproduce**:
Run a query that instantly fails, such as a "Table x does not exist".

**Provide logs (if relevant)**:

```2019/01/14 20:01:37.986 +0000 WARN [PrestoServiceImpl] [Yanagishima] Query 20190114_200137_02486_si2cr has no columns```
	
**Provide screenshots (if relevant)**:
![image](https://user-images.githubusercontent.com/9325534/51137201-2e224380-17f3-11e9-86cc-9dbfc8489773.png)

**Comment by wyukawa** [comment]
It's weird and I can't reproduce it.
By the way, yanagishima requires JDK 1.8.

**Comment by Bcpoole** [comment]
It was caused by us having it deployed under http instead of https and fixed in 18.0. We did still change to https afterwards.
