### ISSUE TITLE
Support for Elasticsearch low version？

### ISSUE THREAD

**Issue by imperio-wxm** [yanagishima/yanagishima#53]
I read the code and find es sql use `unofficial-elasticsearch-jdbc-driver`, but it based on elasticsearch 6.3+'s rest api.

Whether to consider using a more general es jdbc? Like this: https://github.com/NLPchina/elasticsearch-sql

**Comment by ebyhr** [comment]
Thanks for the useful information. At a glance, the repository isn't actually general because it requires to bundle several jars to support multiple versions. Please correct me if I am wrong.
