### ISSUE TITLE
Any plan to provide a docker image ?

### ISSUE THREAD

**Issue by mfilotto** [yanagishima/yanagishima#55]
Would be great if you could generate a docker image on Docker Hub
Thanks for this very usefull tool by the way

**Comment by dkim010** [comment]
Recently, I created the yanagishima docker image.
[docker-yanagishima](https://github.com/dkim010/docker-yanagishima) and [dockerhub](https://hub.docker.com/r/dkim010/yanagishima) can be helpful.
