### ISSUE TITLE
502 Bad Gateway error when trying to download query result

### ISSUE THREAD

**Issue by realyiyu** [yanagishima/yanagishima#64]
**yanagishima version**: think this is 21.0

**presto version**: don't know

**conf/yanagishima.properties**: 

**JVM version** (`java -version`):

**Server OS version** (`uname -a` if on a Unix-like system):

**Client OS version** MacOS Mojave 10.14.6

**Browser**: Chrome

**Description of the problem including expected versus actual behavior**:
Expected behavior: clicking 'Download' on a result downloads a csv or tsv of the result
Actual behavior: clicking 'Download' on a result throws 502 Bad Gateway error

**Steps to reproduce**:
1. Run any query
2. click 'Download'

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) query execution, bookmark, settings, hisotry etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. run any query
 2. Confirm query finishes running and see result in UI
 3. Click 'Download' csv

**Provide logs (if relevant)**:
	
**Provide screenshots (if relevant)**:
![image](https://user-images.githubusercontent.com/52179501/64057852-5b8be980-cb57-11e9-8220-5afd9a601357.png)

**Comment by ebyhr** [comment]
Can you provide the log?

**Comment by realyiyu** [comment]
Sorry, I don't know how to get the log.

**Comment by ebyhr** [comment]
Do you mean you can't access the server, or you don't know the log file path?
