### ISSUE TITLE
schema contains '-' can not be work

### ISSUE THREAD

**Issue by elvizlai** [yanagishima/yanagishima#65]
when database name(schema) contains char '-', it can not describe table info because it missed " wrapper.

![Jietu20190831-074212@2x](https://user-images.githubusercontent.com/501861/64056090-5c5a6500-cbc3-11e9-998f-4df3ef85710b.jpg)

Example:

yanagishima runs somthing like `describe xxx.test-dev.tableName`    

it should be `describe xxx."test-dev"."tableName"`

**Comment by ebyhr** [comment]
Sent PR to fix the query for Presto. Please let me know if you are using other datasource.

**Comment by elvizlai** [comment]
@ebyhr  missing handle button `clipboard`
