### ISSUE TITLE
Query List -> Info URL missing ui

### ISSUE THREAD

**Issue by elvizlai** [yanagishima/yanagishima#66]
When click Info button, it shows
```
HTTP ERROR 404
Problem accessing /query.html. Reason:

    Not Found
```

The url is `/query.html?20190831_000317_00007_9bkkp`

that should be `/ui/query.html?20190831_000317_00007_9bkkp`

**Comment by ebyhr** [comment]
Unfortunately, I couldn't reproduce it. Could you share the detail about Presto & Yanagishima version and yanagishima.properties?

**Comment by elvizlai** [comment]
```
docker stop presto
docker rm presto
docker run -itd \
    --name presto \
    --restart always \
    -p 8000:8080 \
    prestosql/presto:318
```

**Comment by ebyhr** [comment]
I could reproduce it now, thanks for the information.

**Comment by ebyhr** [comment]
Can you try to add below to your yanagishima.properties?
```
presto.redirect.server.<your-presto>=http://localhost:8000/ui
```

**Comment by elvizlai** [comment]
@ebyhr this works, thx
