### ISSUE TITLE
Can you add some configurations that we can add username and password to login in the WEB UI

### ISSUE THREAD

**Issue by JellyMing** [yanagishima/yanagishima#69]
**Describe the feature**:

**yanagishima version**:

**presto version**:

**conf/yanagishima.properties**:

**JVM version** (`java -version`):

**Server OS version** (`uname -a` if on a Unix-like system):

**Client OS version**

**Browser**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) query execution, bookmark, settings, hisotry etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:
	
**Provide screenshots (if relevant)**:

**Comment by ebyhr** [comment]
Hi, is `auth.xxx=true` option not enough your situation?
https://github.com/yanagishima/yanagishima#authentication-and-authorization
