### ISSUE TITLE
How to limit the functions when using it, I mean to limit its operating authorization. I want it to have only access of querying.  How to configure it, Please !

### ISSUE THREAD

**Issue by JellyMing** [yanagishima/yanagishima#87]
**Describe the feature**:

**yanagishima version**:

**presto version**:

**conf/yanagishima.properties**:

**JVM version** (`java -version`):

**Server OS version** (`uname -a` if on a Unix-like system):

**Client OS version**

**Browser**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) query execution, bookmark, settings, hisotry etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:
	
**Provide screenshots (if relevant)**:

**Comment by ebyhr** [comment]
I'm sorry, but I couldn't understand what you want. Would you share the example?

**Comment by JellyMing** [comment]
I'm so sorry to have confused you so much. I mean I want the user to only have access to the query but not create/delete or update and so on. Thank you

**Comment by ebyhr** [comment]
Understood. Thanks for the explanation. Elasticsearch and Hive in Yanagishima have `disallowed.keywords` properties, but the logic has bug. We can bypass it by putting a comment in front of the query. Which driver are you using (Presto)?

**Comment by JellyMing** [comment]
Yes，I am using Presto as my driver and my datasource is Kudu. I deployed Yanagishima as a Web UI for qureying work only. I can't let other people manipulate the data. So I want to know how to configure it. Thanks

**Comment by ebyhr** [comment]
Unfortunately, there's no way to do it in Yanagishima. I would recommend to configure it in Presto layer. https://prestosql.io/docs/current/security/built-in-system-access-control.html

**Comment by JellyMing** [comment]
Thanks for your reminding. I will configure it in Presto layer. Thank you

**Comment by JellyMing** [comment]
Hi，I'm so sorry to bother you again. Because some reason, i need to redevelop yanagishima to implement some permission functions. So may i ask you for a maven project? I am not familiar with gradle so it's  a little hard for me to

redevelop it . Sincerely
    Thank you



--

博学之，审问之，慎思之，明辨之，笃行之。
Best wishes
By—Jelly

At 2019-09-25 15:59:10, "Yuya Ebihara" <notifications@github.com> wrote:


Unfortunately, there's no way to do it in Yanagishima. I would recommend to configure it in Presto layer. https://prestosql.io/docs/current/security/built-in-system-access-control.html

**Comment by ebyhr** [comment]
> So may i ask you for a maven project?

Do you mean migrating to maven project from gradle? Please let us know what you faced issue more detail.

**Comment by JellyMing** [comment]
Yes, you are right, i do mean migrating it to a maven project from gradle . Because in my project , other subprojects  are maven subprojects . So i need a maven version so that i can use it my project








--

博学之，审问之，慎思之，明辨之，笃行之。
Best wishes
By—Jelly

At 2019-09-27 12:11:09, "Yuya Ebihara" <notifications@github.com> wrote:


So may i ask you for a maven project?

Do you mean migrating to maven project from gradle? Please let us know what you faced issue more detail.

**Comment by ebyhr** [comment]
I see. Please try following steps:
1. Add `apply plugin: 'maven'` to build.gradle.
2. Run `gradle install`
3. You can get `pom-default.xml` in the `build/poms` directory

**Comment by JellyMing** [comment]
Thanks for your reply. i have done that many times and it always reports an exception. But i succeed by accdient.
Now i meet another problem as shown in attchment.

  Description:
     when i click the button Treeview, it gives me a report shown at the right hand.
How can i solve it, Please ,thank you








--

博学之，审问之，慎思之，明辨之，笃行之。
Best wishes
By—Jelly

At 2019-09-27 12:23:22, "Yuya Ebihara" <notifications@github.com> wrote:


I see. Please try following steps:

Add apply plugin: 'maven' to build.gradle.
Run gradle install
You can get pom-default.xml in the build/poms directory

**Comment by ebyhr** [comment]
Can you share the screenshot and the error log if exists?

**Comment by JellyMing** [comment]
Sorry, i forget to give you the attchment



--

博学之，审问之，慎思之，明辨之，笃行之。
Best wishes
By—Jelly

At 2019-09-27 15:37:20, "Yuya Ebihara" <notifications@github.com> wrote:


Can you share the screenshot and the error log if exists?

**Comment by ebyhr** [comment]
I guess you are using mailer and I can't see the image. Could you attache the image in GitHub issue?

**Comment by JellyMing** [comment]
Hello,I have put it in the Github issue.
Thank you






--

博学之，审问之，慎思之，明辨之，笃行之。
Best wishes
By—Jelly

在 2019-09-27 15:42:06，"Yuya Ebihara" <notifications@github.com> 写道：


I guess you are using mailer and I can't see the image. Could you attache the image in GitHub issue?

**Comment by JellyMing** [comment]
Hi，I'm so sorry to bother you again. A few days ago you gave me a link https://prestosql.io/docs/current/security/built-in-system-access-control.html. But i found that there are two presto website and i am refer to https://prestodb.github.io/docs/current/security/built-in-system-access-control.html . In this link, It is no allowed to set configuration that some user who has all the rights but others have a read-only rights. I am confused by this two link and could you tell me what's the differences between this two version( i mean perstodb and presto sql), Thank you  !

**Comment by ebyhr** [comment]
You can see the detail in this issue https://github.com/prestosql/presto/issues/380. Most contributors already migrated to prestosql from prestodb and we are focusing on prestosql. I would recommend to join the Slack from https://prestosql.io/slack.html. If you face some issue about Presto (≠Yanagishima), you can get the answer quickly from the community.

**Comment by JellyMing** [comment]
Thank you very much.
