### ISSUE TITLE
How to deploy project  in HTTPS

### ISSUE THREAD

**Issue by Carlbowen** [yanagishima/yanagishima#88]
It's my first time use gradle project.Then I searched a lot of information on the internet, but I couldn't find any way to tell me how to deploy gradle project in HTTPS.
Is anyboby could tell me the way to depoly this project in HTTPS。
Just tell me about the steps or URL links。That would be very good for me. Thanks.

PS:My system environment is centos7.3

**Comment by ebyhr** [comment]
Gradle is just a tool to build Java project and not to affect how we deploy the output jar.

**Comment by Carlbowen** [comment]
> Gradle is just a tool to build Java project and not to affect how we deploy the output jar.
Hi,Gradle.Thanks for your reply.I konw what you mean,but my main problem is how to deploy the project in HTTPS. 
Initially, I configured auth. dev - cluster = true based on readMe,and a "Authentication using username/password requires HTTPS to be enabled" prompt appears on the page. 
Then I config https on http,but I found the project was not affected by http. 
Now I don't know what to do next to "depoly project in HTTPS". If you know, I hope you can tell me the general steps or URL links.
Looking forward to your reply.
Thank.

**Comment by Carlbowen** [comment]
> Gradle is just a tool to build Java project and not to affect how we deploy the output jar.

Hi,Gradle.Thanks for your reply.I konw what you mean,but my main problem is how to deploy the project in HTTPS.
Initially, I configured auth. dev - cluster = true based on readMe,and a "Authentication using username/password requires HTTPS to be enabled" prompt appears on the page.
Then I config https on http,but I found the project was not affected by http.
Now I don't know what to do next to "depoly project in HTTPS". If you know, I hope you can tell me the general steps or URL links.
Looking forward to your reply.
Thank.

**Comment by Carlbowen** [comment]
PS：Details of local environment are as follows
jdk: 1.8
presto: 0.198
system: centos7.3
npm: 6.4.1
node: 10.14.1
yanagishima: 20.0

**Comment by ebyhr** [comment]
As far as I know, this application doesn't support standalone https server. How about using nginx in front of the yanagishima server?
