### ISSUE TITLE
 when i click the button Treeview,  it show me "in test: line 1:37: mismatched input '‘'. Expecting:"

### ISSUE THREAD

**Issue by JellyMing** [yanagishima/yanagishima#89]
**Describe the feature**:

**yanagishima version**:20.0

**presto version**:0.219

**conf/yanagishima.properties**:

**JVM version** (`java -version`):

**Server OS version** (`uname -a` if on a Unix-like system):

**Client OS version**

**Browser**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) query execution, bookmark, settings, hisotry etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:
	
**Provide screenshots (if relevant)**:

![TreeView_exception ](https://user-images.githubusercontent.com/49786680/65751889-3ed6d780-e13e-11e9-8bfa-a69cbaf86272.png)

**Comment by ebyhr** [comment]
Could you share:
1. yanagishima.properties (you can hide confidential info)
2. log message

**Comment by JellyMing** [comment]
I am so sorry. i changed a wrong character in the source code so it reported this. Apologize to you

**Comment by ebyhr** [comment]
No need to apologize. Thanks for your report.
